[package]
name = "ai-api"
version = "0.1.0"
authors = ["Bryan Chen <bryanchen74@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"