[package]
name = "processor"
version = "0.1.0"
edition = "2018"

[dependencies]
common = { path = "../common" }
rand = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
termion = "1.5"
