[package]
name = "pc-finder"
version = "0.1.0"
authors = ["Bryan Chen <bryanchen74@gmail.com>"]
edition = "2018"

[dependencies]
common = { path = "../common" }
serde = "1"
serde_json = "1"
rayon = "1.5"
bson = "2.0"

[profile.release]
debug = true
# lto = true
