[package]
name = "rusty-ai"
version = "0.1.0"
authors = ["Bryan Chen <bryanchen74@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
byteorder = "1.4"
base65536 = "1.0"
dashmap = "4.0"
common = { path = "../common" }
rand = { version = "0.8", optional = true }
rand_distr = { version = "0.4", optional = true }
ctrlc = { version = "3.1", optional = true }


[features]
default = []
trainer = ["rand", "rand_distr", "ctrlc"]

[[bin]]
name = "train"
required-features = ["trainer"]

[profile.release]
debug = true